begin
  require 'rspec/core/rake_task'

  RSpec::Core::RakeTask.new(:spec) do |t|
  t.rspec_opts = "-c --format d --fail-fast"
  t.verbose = false
  end

  task :default => :spec
rescue LoadError
# no rspec available
end
