# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41809a633ad04d333e0c0f9d8b4daec15ca7eb54e5d75e17066c54bcea0ed44f0a6769c3ec00284dd828c2b44cbc873645257045b4289098c970b6902fd10d1a

test:
  secret_key_base: 8249e1aa8b53bcd2879d019b18e0574ec6231cd3698c34d60810ce81dcceb7c6bca142f6826474451e1de0641f1a5d5d1d6eadd4286150fa3557475a8649a0e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
