source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.4'
# Use postgresql as the database for Active Record
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

gem 'will_paginate', '~> 3.0.6'

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'devise', '~> 3.5', '>= 3.5.6'

gem 'omniauth', '~> 1.3', '>= 1.3.1'

gem 'bootstrap-sass', '~> 3.3', '>= 3.3.6'
gem 'autoprefixer-rails'

gem 'database_cleaner'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'growl_notify', '~> 0.0.3' # on mac shows a notification when guard runs tests

end

group :development, :test do
  gem 'byebug' # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'minitest' # otherwise rspec bugs out
  gem "spring-commands-rspec"
  gem 'rspec-rails' # test framework. !Use rails g rspec:install after bundlemail adresses and names!
  gem 'factory_girl_rails' # replaces Rails’ default fixtures for feeding test data to the test suite with much more preferable factories
  gem 'faker' # populates test data with fake e
end

group :test do
  #gem 'turn' # pretty printing for test results
  gem 'capybara' # integration test framework
  gem 'launchy' # launches browser as soon as an integration test fails to show what the application renders    
  gem 'guard-rspec' # automatically runs test when changes. replaces rake test. run guard init rspec after rspec install
  
  gem "letter_opener" # opens mail send in webpage instead of sending them. requires changed setting in config/environments/development.rb file.
  gem 'shoulda-matchers' # provides some extra matchers for rspec
end



