# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7c1479b6284687ad484f663a518753ae8f58482c86fadb1f8b81c411e448457827fd3120d4f7aa434295039befeabed2993a90f5639d493b2afd9d5ac2b397f

test:
  secret_key_base: d2ad72681110829e9edfcdd9b3b472e9f287bd5d725a39ea6f82c85de1191c2ff004c3be1ad0679f246748ddca9caf9d724a4160fb791bb6b0a2d38992310670

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
