# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 964bbcca9ee206acd0c4b855342c208288bafd4b0c816fff3c9cab4e332b98440aeda5b51a95bb5dfd3245b597c3e4a10710e96ce186e550c711a73e21a7cf9e

test:
  secret_key_base: 4b17478091cc6f3a44cf42f49dfba24efd62ab1c6a121d50ad36991d05d7d744bcdd9feebd99a84bf86f6435774a55e4fdb2fad6760238b221dc00a822fc7613

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
